### ISSUE TITLE
pip install returns an error "FileNotFoundError: [Errno 2] No such file or directory: 'README.md'"

### ISSUE THREAD

**Issue by sash-ko** [flix-tech/RevPy#8]
```bash
Collecting revpy
  Downloading revpy-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q3/sm0jm7hx35jgs78lcnnx83s40000gn/T/pip-build-mr2dyna6/revpy/setup.py", line 11, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

Python version: 3.5.2
OS: macOs Sierra

**Comment by jdoepfert** [comment]
I included README.md in the MANIFEST. Should work now

**Comment by sash-ko** [comment]
thanks!
